function Qdotdot = Compute_Accel(I1,Q1,T1,g,m1,r1)
%COMPUTE_ACCEL
%    QDOTDOT = COMPUTE_ACCEL(I1,Q1,T1,G,M1,R1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    24-Jan-2018 22:46:19

Qdotdot = (T1-g.*m1.*r1.*cos(Q1))./(I1+m1.*r1.^2);
