function UF = Compute_Potential(Q1,g,m1,r1)
%COMPUTE_POTENTIAL
%    UF = COMPUTE_POTENTIAL(Q1,G,M1,R1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    24-Jan-2018 22:46:19

UF = g.*m1.*r1.*sin(Q1);
