function KF = Compute_Kinetic(I1,Q1,Q1dot,m1,r1)
%COMPUTE_KINETIC
%    KF = COMPUTE_KINETIC(I1,Q1,Q1DOT,M1,R1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    24-Jan-2018 22:46:19

t2 = sin(Q1);
t3 = Q1dot.^2;
t4 = r1.^2;
t5 = cos(Q1);
KF = I1.*t3.*(1.0./2.0)+m1.*(t2.^2.*t3.*t4+t3.*t4.*t5.^2).*(1.0./2.0);
