function accel = compute_accel(I,Q,Qdot,g,m,r)
%COMPUTE_ACCEL
%    ACCEL = COMPUTE_ACCEL(I,Q,QDOT,G,M,R)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    24-Jan-2018 22:52:18

t2 = Qdot.^2;
t3 = r.^2;
accel = (I.*t2.*(1.0./2.0)+m.*t2.*t3.*(1.0./2.0)-g.*m.*r.*cos(Q))./(I+m.*t3);
