function Tsave = compute_kinetic(I,Qdot,m,r)
%COMPUTE_KINETIC
%    TSAVE = COMPUTE_KINETIC(I,QDOT,M,R)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    24-Jan-2018 22:52:17

t2 = Qdot.^2;
Tsave = I.*t2.*(1.0./2.0)+m.*r.^2.*t2.*(1.0./2.0);
