function Usave = compute_potential(Q1,Q2,g,l1,m1,m2,r1,r2)
%COMPUTE_POTENTIAL
%    USAVE = COMPUTE_POTENTIAL(Q1,Q2,G,L1,M1,M2,R1,R2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    24-Jan-2018 22:29:51

t2 = sin(Q1);
Usave = g.*m2.*(l1.*t2+r2.*sin(Q1+Q2))+g.*m1.*r1.*t2;
