function accel = compute_accel2(Q1,Q2,Q1dot,Q2dot,T1,T2,g,l1,l2,m1,m2)
%COMPUTE_ACCEL2
%    ACCEL = COMPUTE_ACCEL2(Q1,Q2,Q1DOT,Q2DOT,T1,T2,G,L1,L2,M1,M2)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    08-Feb-2016 17:35:33

t2 = l1.^2;
t3 = cos(Q2);
t4 = l2.^2;
t5 = sin(Q2);
t6 = cos(Q1);
t7 = Q1dot.^2;
t8 = m2.^2;
t9 = t3.^2;
t10 = Q1+Q2;
t11 = cos(t10);
t12 = Q2dot.^2;
accel = [(T1.*l2-T2.*l2-T2.*l1.*t3-g.*l1.*l2.*m1.*t6-g.*l1.*l2.*m2.*t6+l1.*m2.*t4.*t5.*t7+l1.*m2.*t4.*t5.*t12+l2.*m2.*t2.*t3.*t5.*t7+Q1dot.*Q2dot.*l1.*m2.*t4.*t5.*2.0+g.*l1.*l2.*m2.*t3.*t11)./(l2.*m1.*t2+l2.*m2.*t2-l2.*m2.*t2.*t9),-(-T2.*m1.*t2-T2.*m2.*t2+T1.*m2.*t4-T2.*m2.*t4+T1.*l1.*l2.*m2.*t3-T2.*l1.*l2.*m2.*t3.*2.0-g.*l1.*t4.*t6.*t8+g.*l2.*t2.*t8.*t11-g.*l2.*t2.*t3.*t6.*t8+g.*l1.*t3.*t4.*t8.*t11+l1.*l2.*t2.*t5.*t7.*t8+l1.*l2.*t4.*t5.*t7.*t8+l1.*l2.*t4.*t5.*t8.*t12+t2.*t3.*t4.*t5.*t7.*t8.*2.0+t2.*t3.*t4.*t5.*t8.*t12-g.*l1.*m1.*m2.*t4.*t6+g.*l2.*m1.*m2.*t2.*t11+Q1dot.*Q2dot.*l1.*l2.*t4.*t5.*t8.*2.0+Q1dot.*Q2dot.*t2.*t3.*t4.*t5.*t8.*2.0-g.*l2.*m1.*m2.*t2.*t3.*t6+l1.*l2.*m1.*m2.*t2.*t5.*t7)./(t2.*t4.*t8+m1.*m2.*t2.*t4-t2.*t4.*t8.*t9)];
